// Generated by CoffeeScript 1.7.1
(function() {
  var L, ROW_TEMPLATE,
    __slice = [].slice;

  L = function() {
    var things;
    things = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return console.log.apply(console, things);
  };

  ROW_TEMPLATE = "<tr><td></td><td></td><td></td><td></td><td></td><td></td></tr>";

  d3.json('/mk8.min.json', function(err, json_data) {
    var table_body;
    if (err) {
      throw 'Error getting data';
    }
    this.characters = json_data["Characters"];
    this.vehicles = json_data["Vehicles"];
    this.karts = json_data["Vehicles"]["Karts"];
    this.bikes = json_data["Vehicles"]["Bikes"];
    this.wheels = json_data["Wheels"];
    L(characters);
    L(vehicles);
    L(wheels);
    table_body = d3.select('tbody');
    return table_body.selectAll('tr').data(d3.entries(characters)).enter().append('tr').html(function(d, i) {
      return "<td>" + d.key + "</td><td>" + d.value.Acceleration + "</td>";
    });
  });

}).call(this);

//# sourceMappingURL=mk8.d3.map
